name: Unit Tests 🧪
on:
  pull_request:
    branches:
      - 'dev*'
      - 'releases/v*'
  push:
    branches:
      - '*'
    tags-ignore:
      - '*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and build
        run: 
          npm install 
          npm run build
